apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: stream-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stream-web
  template:
    metadata:
      labels:
        name: stream-web
    spec:
      containers:
        - name: stream-web
          command: [
		    "/stream-web"
          ]
          env:
          - name: MICRO_REGISTRY
            value: "etcd"
          - name: MICRO_REGISTRY_ADDRESS
            value: "etcd-cluster-client"
          - name: MICRO_REGISTER_TTL
            value: "60"
          - name: MICRO_REGISTER_INTERVAL
            value: "30"
          - name: MICRO_CLIENT_RETRIES
            value: "3"
          image: microhq/stream-web
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: web-port
