version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.6
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
            touch .env
      - run:
          name: "Run Tests"
          command: |
            make test ARGS='-v -race -count=2 -coverprofile=coverage.txt -covermode=atomic ./...'
      - run:
          name: "Run Linter"
          command: |
            golangci-lint run --no-config --issues-exit-code=1 --enable-all --disable=vetshadow --disable=gocyclo --disable=unparam --disable=nakedret --disable=lll --disable=dupl --disable=gosec --disable=gochecknoinits --disable=gochecknoglobals --tests=false
            golangci-lint run --no-config --issues-exit-code=0 --disable-all --enable=vetshadow --enable=gocyclo --enable=unparam --enable=nakedret --enable=lll --enable=dupl --enable=gosec --enable=gochecknoinits --enable=gochecknoglobals --deadline=120s
      - run:
          name: "Upload Coverage"
          command: bash <(curl -s https://codecov.io/bash)
