apiVersion: v1
kind: Service
metadata:
  name: micro-network
  namespace: default
  labels:
    name: micro-network
    micro: runtime
spec:
  type: NodePort
  ports:
  - port: 8085
    protocol: UDP
    name: network
    nodePort: 30038
  selector:
    name: micro-network
    micro: runtime
---
apiVersion: v1
kind: Service
metadata:
  name: micro-gateway
  namespace: default
  labels:
    name: micro-gateway
    micro: runtime
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: service
  selector:
    name: micro-network
    micro: runtime
