apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-runtime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-runtime
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - update
  - delete
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-runtime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-runtime
subjects:
- kind: ServiceAccount
  name: micro-runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-runtime
  labels:
    micro: runtime
    name: micro-runtime
  annotations:
    name: "go.micro.runtime"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-runtime
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-runtime
        micro: runtime
    spec:
      serviceAccountName: micro-runtime
      containers:
      - name: runtime
        env:
        - name: MICRO_BROKER
          value: "nats"
        - name: MICRO_BROKER_ADDRESS
          value: "nats-cluster"
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        - name: MICRO_RUNTIME
          value: "kubernetes"
        - name: MICRO_AUTO_UPDATE
          value: "true"
        - name: MICRO_LOG_LEVEL
          value: "debug"
        command:
        - /micro
        - runtime
        image: micro/micro
        imagePullPolicy: Always
