on: "3.7"

services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - micro-net
  api:
    command: --registry=etcd --registry_address=etcd:2379 api --address=0.0.0.0:8080
    image: micro/micro
    ports:
      - "8080:8080"
    networks:
      - micro-net

  proxy:
    command: --registry=etcd --registry_address=etcd:2379 --address=0.0.0.0:8081
    image: micro/micro
    ports:
      - "8081:8081"
    networks:
      - micro-net
  web:
    deploy:
      replicas: 3
    command:  --registry=etcd --registry_address=etcd:2379 --address=0.0.0.0:8082
    image: micro/micro
    ports:
      - "8082:8082"
    networks:
      - micro-net

networks:
  micro-net:
    external: true
