language: go
go:
- 1.13.x
env:
  - GO111MODULE=on
notifications:
  slack:
    secure: hJZEXQA4WpiEopu0kjYLTm9I30ZkWPUyDQyZgpufHmLzW6XGayMOcYcI+dSVZl4a6lid4px9gAAnTUUA5NZoFcKrWPMfNX2BnIvW/wpm2yKrW5rdpIlnT07YefeFRUa2l47ifSnTwr+aPsfM0TjIQB2Ep8NsrtvmbaaE1xMXgI8=
cache:
  directories:
    - $GOPATH/pkg/mod
