apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-srv
  template:
    metadata:
      labels:
        name: greeter-srv
    spec:
      containers:
      - name: greeter
        command: [
          "/greeter-srv",
          "--server_address=0.0.0.0:8080",
          "--broker_address=0.0.0.0:10001"
        ]
        env:
        - name: MICRO_REGISTRY
          value: "etcd"
        - name: MICRO_REGISTRY_ADDRESS
          value: "etcd-cluster-client"
        image: microhq/greeter-srv
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: greeter-port
